name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./
      run: docker build . testapplicationv2/Dockerfile --tag thisoban/testaplicationv2:latest
    - name: publish
      run: |
          docker login -u thisoban -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push thisoban/testing:latest
