name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build -f Dockerfile -t thisoban/testing:latest testapplicationv2/
    - name: publish
      run: |
          docker login -u thisoban -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push thisoban/testing:latest
